In [1]:
import numpy as np;
import matplotlib.pyplot as plt;
import pickle;
import scipy.special;

# Read data from pickle

In [4]:
prefix = "data/v5_"
n = "3"

file = open(prefix + "etheta_" + n + ".pkl", "rb");
xsdata=pickle.load(file);
#print("Loaded ",len(xsdata),"data sets");

file = open(prefix + "xsdata_" + n +".pkl", "rb");
info=pickle.load(file);
#print(info);

file = open(prefix + "info_" + n + ".pkl", "rb");
etheta=pickle.load(file);
#print(etheta);


# Look at some of the data

In [5]:
for index in range(1) : #len(info)) :
    print(info[index]);
    
    # The following for plotting purposes only
    
    # Creating plot
    e     = etheta["E"];
    theta = etheta["theta"];
    xs    = xsdata[index];
    
    # Adjust for wireframe plotting
    
    theta_grid, e_grid = np.meshgrid(theta,e);
    print(e_grid.shape);
    print(e_grid);
    print(theta_grid);

    legendre_grid = scipy.special.eval_legendre(0,np.cos(theta_grid))**2;

    #print(legendre_grid.shape)
    #print(legendre_grid);
    
    
    xs_grid = np.reshape(xs,e_grid.shape)/legendre_grid;
    
    # Creating figure
    fig = plt.figure(figsize = (10, 7))
    ax = plt.axes(projection ="3d");
    ax.plot_wireframe(theta_grid,e_grid,xs_grid, color = "red")
    plt.title("N_res="+str(np.round(info[index]["n_res"],3)));
    ax.view_init(30, 60)
    plt.show()

    print(xs.shape)
    print(legendre_grid.shape);
    
    fig = plt.figure(figsize = (10, 7))
    plt.title("N_res="+str(np.round(info[index]["n_res"],3)));
    plt.imshow(xs/legendre_grid,aspect='auto');
plt.show();


[[-0.7993 -0.7935 -0.905  ... -0.1242 -0.2141 -0.2896]
 [-0.849  -0.841  -0.948  ... -0.1252 -0.2161 -0.2922]
 [-0.8975 -0.888  -0.9917 ... -0.1262 -0.2181 -0.2952]
 ...
 [-0.756  -0.6284  0.3396 ...  4.29    3.67    3.037 ]
 [-0.7705 -0.607   0.3765 ...  4.324   3.71    3.086 ]
 [-0.7964 -0.587   0.4187 ...  4.363   3.758   3.14  ]]


TypeError: list indices must be integers or slices, not str